# Generated by Django 4.2.1 on 2023-06-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creater',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
