# Generated by Django 4.2.1 on 2023-06-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_failedlogins'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedlogins',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
