# Generated by Django 4.2.1 on 2023-06-09 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_failedlogins_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedlogins',
            name='time_stamp',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
