# Generated by Django 4.2.1 on 2023-06-09 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_failedlogins_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedlogins',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
