# Generated by Django 4.2.1 on 2023-06-12 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_failedlogins_count_passwordrecovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrecovery',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 16, 56, 22, 264039)),
        ),
    ]
